spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cursospring
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: never
    include-exception: true